# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive

# Configure guest hostname
sudo bash -c 'echo 127.0.1.1 yunohost.yunohost.org yunohost >> /etc/hosts'
sudo hostname yunohost.yunohost.org
sudo bash -c 'echo yunohost.yunohost.org > /etc/hostname'

# Define root password
echo -e "yunohost\nyunohost" | sudo passwd root

# Allow sudo removal (YunoHost use sudo-ldap)
export SUDO_FORCE_REMOVE=yes

# Upgrade guest (done in install script)
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade

# Install YunoHost
sudo apt-get install git -y
sudo git clone https://github.com/YunoHost/install_script --branch stretch
sudo bash -c 'cd install_script && ./install_yunohost -a'
sudo rm -r /ynh-dev/

# Cleanup
sudo apt-get clean -y
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Default folder sharing
  config.vm.synced_folder ".", "/vagrant"
  # Force guest type, because YunoHost /etc/issue can be tuned
  config.vm.guest = :debian
  
  # Debian Jessie with YunoHost stable release
  config.vm.define "jessie-stable", primary: true do |stable|
    stable.vm.box = "debian/contrib-jessie64"
    stable.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'stable'"
    end
    stable.vm.network :private_network, ip: "192.168.33.80"
  end

  # Debian Jessie with YunoHost testing release
  config.vm.define "jessie-testing" do |testing|
    testing.vm.box = "debian/contrib-jessie64"
    testing.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'testing'"
    end
    testing.vm.network :private_network, ip: "192.168.33.81"
  end

  # Debian Jessie with YunoHost unstable (nightly) release
  config.vm.define "jessie-unstable" do |unstable|
    unstable.vm.box = "debian/contrib-jessie64"
    unstable.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    unstable.vm.network :private_network, ip: "192.168.33.82"
  end

  # Debian Stretch with YunoHost unstable (nightly) release
  config.vm.define "stretch-unstable" do |unstable|
    unstable.vm.box = "debian/stretch64"
    unstable.vm.provision "shell" do |s|
      s.inline = $script
      s.args   = "'unstable'"
    end
    unstable.vm.network :private_network, ip: "192.168.33.93"
  end


end
